# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4157c4b97f0467693e62f0a929d93aaa15a459231d2c60baaf53fa7ecca8a4436872d71bf943f54435cef8ea451b02cf075efc420db5effeeb53e7a968252e55

test:
  secret_key_base: bae4d02e8f6c8ae21cf563674f0e035926273b96f9add45f877deabc47860f0b9715dacbff6e84c1f9c188fb239087da7f179ec2cde1b4cfd7a29e3cdda92226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
